apiVersion: v1
kind: Service
metadata:
  name: hotelia-teacher-function-service
  labels:
    app: hotelia-teacher-function
spec:
  type: NodePort
  selector:
    app: hotelia-teacher-function
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
